[project]
name = "sigil"
version = "0.0.1"
description = "Sigil Programming Language"
readme = "README.md"
requires-python = ">=3.11.11"
dependencies = ["llvmlite>=0.44.0"]

[dependency-groups]
dev = ["ruff>=0.13.0", "pytest>=8.4.2"]

[tool.ruff]
line-length = 120
