[project]
name = "sigil"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.11"
dependencies = [
    "llvmlite>=0.44.0",
]

[dependency-groups]
dev = [
    "ruff>=0.13.0",
    "pytest>=8.4.2",
]
